# Use root/example as user/password credentials

services:

  db:
    image: mysql
    restart: always
    container_name: "mysql-user-database"
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=employees
    # (this is just an example, not intended to be a production configuration)
